rewrited getAllcertificates and fixed generating certificates
ita-social-projects/horondi_client_be pull request #1145
Opened 2022-03-23 22:59 UTC by SirAndrii

## Description

Added sorting and searching functionality to gerAllCertifcate method.
Rewrote quering with aggregate.
Fixed tests and input for generating certificates for admin part

#### Screenshots

### Checklist
- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date front-end and admin part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-04-05 19:10 UTC, rostyslaw27 approved these changes

2022-04-05 19:27 UTC, rostyslaw27 requested changes

2022-04-05 19:27 UTC, rostyslaw27 commented on modules/certificate/certificate.service.js
> +  async getCertificatesByPaymentToken(paymentToken) {
We no longer need this function

2022-04-05 19:51 UTC, SirAndrii commented on modules/certificate/certificate.service.js
> +  async getCertificatesByPaymentToken(paymentToken) {
was added by rebase. Fixed.

2022-04-05 20:06 UTC, rostyslaw27 submitted a review, later dismissed

2022-04-06 15:23 UTC, maarekua approved these changes

2022-04-06 16:34 UTC, rostyslaw27 approved these changes

2022-04-06 16:35 UTC, Yevhendzyuba approved these changes

2022-04-06 16:36 UTC, DeLettenhove approved these changes

2022-04-06 16:36 UTC, merged