Feature/#1199/add filtration and sorting for promo codes
ita-social-projects/horondi_client_be pull request #1204
Opened 2022-04-28 20:00 UTC by anjtka333

## Description
Filtration for promocodes added

### Checklist
- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅All tests passed locally
- [x] ✨My changes working with up-to-date front-end and admin part locally, like charm
- [x] 🔗 Link pull request to issue

2022-05-06 07:51 UTC, maarekua requested changes

2022-05-06 07:51 UTC, maarekua commented on helpers/filter-helper.js
> +    if (Object.keys(searchFilter).length) {
Remove if.

2022-05-06 07:51 UTC, maarekua commented on helpers/filter-helper.js
> +  filterByDateOrName(filter, search) {
(filter = {}, search = '')

2022-05-06 07:51 UTC, maarekua commented on helpers/filter-helper.js
> +    const searchTrimmed = (search ?? '').trim();
search ?? - remove

2022-05-06 07:51 UTC, maarekua commented on helpers/filter-helper.js
> +    const regDate = /^\d+[.]\d+[.]\d+$/;
remove regexp

2022-05-06 07:51 UTC, maarekua commented on helpers/filter-helper.js
> +    if (regDate.test(searchTrimmed)) {
remove reg if

2022-05-09 11:37 UTC, maarekua commented on helpers/filter-helper.js
> +      filter['$and'] = [];
filter['$and'] = [searchFilter];

2022-05-20 07:37 UTC, maarekua approved these changes

2022-05-23 11:15 UTC, maarekua approved these changes

2022-05-23 11:20 UTC, Yevhendzyuba approved these changes

2022-05-25 07:10 UTC, merged