added material and news JOI validation
ita-social-projects/horondi_client_be pull request #649
Opened 2021-05-19 19:25 UTC by ostgit12

2021-05-20 14:50 UTC, yuliiakucher commented on modules/news/news.permissions.js
>  const { ADMIN, SUPERADMIN } = roles;
same

2021-05-20 14:52 UTC, yuliiakucher commented on validators/material.validator.js
> +};
please don't duplicate this part, create languageValidator for this case

2021-05-20 14:54 UTC, yuliiakucher commented on validators/material.validator.js
> +  value: Joi.string().trim(),
please add min, max and required

2021-05-20 14:58 UTC, yuliiakucher commented on validators/material.validator.js
> +const languageSchemaValidator = {
please change languageSchemaValidator into a function, that will take min and max as arguments. It should return joi schema.

2021-05-20 15:01 UTC, yuliiakucher commented on validators/news.validator.js
> +    image: Joi.string().trim(),
please don't validate image

2021-05-20 15:03 UTC, yuliiakucher requested changes
please fix comments

2021-05-24 20:26 UTC, RevylaV commented
Fix tests please

2021-06-23 18:29 UTC, Elugormo submitted a review, later dismissed
Resolve conflicts on your branch please and update it to the current development origin version. And check the CI.
Please write a proper description and please unbind PR from the project.

2021-09-06 20:37 UTC, ostgit12 commented on modules/material/material.permissions.js
>  const { ADMIN, SUPERADMIN } = roles;
destruct row 3

2021-09-09 12:47 UTC, yuliiakucher approved these changes

2021-09-14 13:26 UTC, Skrekliam approved these changes

2021-09-14 13:27 UTC, martagorpinchuk approved these changes

2021-09-14 13:27 UTC, merged